/*******************************************************************************
 * Copyright (c) 2024 Eclipse contributors and others.
 *
 * This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License 2.0
 * which accompanies this distribution, and is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *     Eclipse contributors - initial API and implementation
 *******************************************************************************/
package org.eclipse.pde.api.tools.model.tests;

import static org.junit.Assert.assertTrue;

import org.eclipse.pde.api.tools.internal.FilterStore;
import org.eclipse.pde.api.tools.internal.problems.ApiProblemFactory;
import org.eclipse.pde.api.tools.internal.provisional.descriptors.IElementDescriptor;
import org.eclipse.pde.api.tools.internal.provisional.problems.IApiProblem;
import org.junit.Test;

/**
 * Tests for regressions in filter matching logic
 * 
 * This tests the scenario where filters with simple type names in message
 * arguments should match problems with fully qualified type names.
 * 
 * @see https://github.com/eclipse-pde/eclipse.pde/issues/2096
 */
public class FilterMatchingRegressionTests {

	/**
	 * Tests that a filter with simple type names in message arguments
	 * matches a problem with fully qualified type names.
	 * 
	 * This simulates the JDT scenario where .api_filters has simple names
	 * but headless builds generate fully qualified names.
	 */
	@Test
	public void testFilterMatchesWithSimpleAndQualifiedNames() {
		// Create a filter problem with simple names (as stored in .api_filters)
		String[] filterMessageArgs = new String[] { "IDocElement", "AbstractTagElement" };
		IApiProblem filterProblem = ApiProblemFactory.newApiProblem(
				"dom/org/eclipse/jdt/core/dom/AbstractTagElement.java", // path
				"org.eclipse.jdt.core.dom.AbstractTagElement", // type name (fully qualified)
				filterMessageArgs, // message args (simple names)
				null, null, -1, -1, -1,
				IApiProblem.CATEGORY_USAGE,
				IElementDescriptor.TYPE,
				IApiProblem.API_LEAK,
				IApiProblem.NO_FLAGS);

		// Create an actual problem with fully qualified names (as generated by headless build)
		String[] problemMessageArgs = new String[] { "org.eclipse.jdt.core.dom.IDocElement", "org.eclipse.jdt.core.dom.AbstractTagElement" };
		IApiProblem actualProblem = ApiProblemFactory.newApiProblem(
				"dom/org/eclipse/jdt/core/dom/AbstractTagElement.java", // path
				"org.eclipse.jdt.core.dom.AbstractTagElement", // type name (fully qualified)
				problemMessageArgs, // message args (fully qualified)
				null, null, -1, -1, -1,
				IApiProblem.CATEGORY_USAGE,
				IElementDescriptor.TYPE,
				IApiProblem.API_LEAK,
				IApiProblem.NO_FLAGS);

		// Create a filter store to test the matching
		TestFilterStore store = new TestFilterStore();
		
		// Test that the problems match
		boolean matches = store.testProblemsMatch(filterProblem, actualProblem);
		
		assertTrue("Filter with simple names should match problem with fully qualified names", matches);
	}

	/**
	 * Tests that a filter with simple type names matches a problem with simple type names
	 * (IDE scenario)
	 */
	@Test
	public void testFilterMatchesWithBothSimpleNames() {
		// Create a filter problem with simple names
		String[] filterMessageArgs = new String[] { "IDocElement", "AbstractTagElement" };
		IApiProblem filterProblem = ApiProblemFactory.newApiProblem(
				"dom/org/eclipse/jdt/core/dom/AbstractTagElement.java",
				"org.eclipse.jdt.core.dom.AbstractTagElement",
				filterMessageArgs,
				null, null, -1, -1, -1,
				IApiProblem.CATEGORY_USAGE,
				IElementDescriptor.TYPE,
				IApiProblem.API_LEAK,
				IApiProblem.NO_FLAGS);

		// Create an actual problem with simple names (as generated by IDE)
		String[] problemMessageArgs = new String[] { "IDocElement", "AbstractTagElement" };
		IApiProblem actualProblem = ApiProblemFactory.newApiProblem(
				"dom/org/eclipse/jdt/core/dom/AbstractTagElement.java",
				"org.eclipse.jdt.core.dom.AbstractTagElement",
				problemMessageArgs,
				null, null, -1, -1, -1,
				IApiProblem.CATEGORY_USAGE,
				IElementDescriptor.TYPE,
				IApiProblem.API_LEAK,
				IApiProblem.NO_FLAGS);

		TestFilterStore store = new TestFilterStore();
		boolean matches = store.testProblemsMatch(filterProblem, actualProblem);
		
		assertTrue("Filter with simple names should match problem with simple names", matches);
	}

	/**
	 * Helper class to expose the protected problemsMatch method for testing
	 */
	private static class TestFilterStore extends FilterStore {
		public boolean testProblemsMatch(IApiProblem filterProblem, IApiProblem problem) {
			return problemsMatch(filterProblem, problem);
		}
	}
}
